sudo: required

language: java
jdk: oraclejdk8



env:
  global:
      - secure: "H8IJaccCn3YZYB9w+DehZnWhrarQeMkU/QZEkhdU/P/9PWsxJUXKlB5bVNdMVMPTkH2av9mctRB1cYm2f9gfDnYvg4LvnxAyu5i7p0jehaEr5QIaUQ+0gcCxkTaB5VpzLw2xfYY4bkEHDClWqEnAuOfrqdmLMJ0oQJUwsky+thlJX/VCgJ/iSU0x26EyAHmcSXoJ1rlMelQAT0Gc8kqSLbl0Cs+F8R8/te8FKV1IzUAre+dvQJe5PO6MjqJcQC8T6kL7346Kv8xaSGJrl8FfKDoBgLWBjuUMADRadsdPs9CvQFTyfDnQZTiA4MpiceY1WSonZDoqZ1JFIldNRtTcEnlvlQ+F9AxmVQwS4DbO0Hl5Bxa1en9Y90+rxrzY5MRnRGRl67ZX6XXMkgnOsogB+RN3wtMMXCXHyp8Edx6gSqr8Uqna7r7IQvWE+KUWvtJ977jB4y3KOHo7/Uz7VxU8C3bndUpF3tTNT+cEBLDAy5iC6YmLiNRr6F/TOvu+StBfUiF9K0tZNDIq4TDbDCD6ZTzku1JG0K23F8FxQnr1mGFnW8bzVPhLaefZPdjXjsN2eeadAe2RCUFqYjEv/W4U+fgn2Ae7Rao5Xxyh7nkGSRjCGObAXx/mhymYgQklsLGNX4NAkgl3PgqBbpxF1lHBxgbs/qzobrF1PfOYpcBaMvU=" #DOCKER_USER
      - secure: "nljT4myJSpdaMaUEspJBa73qhF/WXc8TVSV4jcyIm6fw0zQ7oZaFoyzpNa3wO8YaPsJcTiiSql9bsHoJygqS3V2/1nf4p81lLGDxa2lLXuT0HOoGOTqjtmcJIngGZ6T3vz/mAuJY+/lWa2YX2yyP4xLCbBA1z/kF9L6bdjyYIJrjp3SASCsFMDJu3nUhlZSOtKUyZxTcdxneogUrSgzyDK5Sy6ljXOc5AyeuJFJfjpZ9zY9Yw0Rw6VbBtb9yiNIVTB9QkcF244L7sizk3rk9V9QXggWV+JRg/XboMTF0IMGpuYyrzzMY/LfhtlAeENAiK7ahmHZO/joh5Xp7dzWUiF0VNNC9PKqbKS226oRu8TJ9Uvxm0iGUOBUkbuYsuQxBTfw3oKgercuprgz5X3WmdUxCrsbBhjH9eGoPpi56xmTaxp0HmqZjzt6w5Z75zvnosk6Q6y9RfFIvJCs+w7BrG31W2lBedlFTM0UU8HjUFBbtTZpo8+MQ7caoiIHmjjr63sVlwUgsfemGKUclPp1WwQ+Mj1SGDp7r0KWOLSTCbyOFBbijVjByQHqoIfV48kqEy7HmnWG6bk5sGWcX/LI/HIbk0bG5fF443HFkWSobzhrXoBUoSbv1A2NDHNU0OFBYB+TLB/JKLlgLASatPO4+Bg8uSStCK/NVTRZgsseJloM=" #DOCKER_PASS
      - COMMIT=${TRAVIS_COMMIT::7}


after_success:
   - docker login --username $DOCKER_USER --password $DOCKER_PASS

  #TAG
   - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  #BUILD
   - export HELLO=rolandjurd/hello-service
   - docker build -t $HELLO:$COMMIT .
   - docker tag $HELLO:$COMMIT $HELLO:$TAG
   - docker push $HELLO



services:
- docker