apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-service
  name: hello-service
  namespace: hellodemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          image: rolandjurd/hello-service
          livenessProbe:
            httpGet:
              port: 8000
              path: /hello/test
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /hello/test
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 3
          ports:
          - containerPort: 8000
